name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [1, 2, 3, 4]  # Define quantas instâncias você quer rodar em paralelo

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests in parallel
        run: |
          npx cypress run --spec "cypress/e2e/**/*.cy.js" --parallel --ci-build-id ${{ github.run_id }}